describe('Form', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3000/')
    })
    it('SHould cbe able to select the form and fill out with information', () => {
        cy.get('input[name="name"]')
            .type('Ryan')
            .should('have.value', 'Ryan')
        cy.get('input[name="date"]')
            .type('5/27')
            .should('have.value', '5/27')
        cy.get('input[name="time"]')
            .type('9:00')
            .should('have.value', '9:00')
        cy.get('input[name="number"]')
            .type('3')
            .should('have.value', '3')
    })

    it("should be able to submit a resrvation and see that displayed", () => {
        cy.get('input[name="name"]')
            .type('Ryan')
            .should('have.value', 'Ryan')
        cy.get('input[name="date"]')
            .type('5/27')
            .should('have.value', '5/27')
        cy.get('input[name="time"]')
            .type('9:00')
            .should('have.value', '9:00')
        cy.get('input[name="number"]')
            .type('3')
            .should('have.value', '3')
        cy.get('button').first().click()
        cy.get('section')
            .get('div')
            .contains('Ryan')
    })
})